---
abstract: 'SVG::Convert XAML driver.'
author: 'Toru Yamaguchi <zigorou@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: SVG-Convert-Driver-XAML
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  FindBin: 0
  Getopt::Long: 0
  Path::Class: 0
  Pod::Usage: 0
  SVG::Convert: 0.02
  XML::LibXML: 0
  XML::LibXSLT: 0
version: 0.02
